'use strict';

module.exports = {
  env: {
    jest: true,
  },
  plugins: ['eslint-plugin-jest'],
  rules: {
    'consistent-test-it': 'error',
    'expect-expect': 'error',
    'lowercase-name': [
      'error',
      {
        ignore: ['describe'],
      },
    ],
    'no-alias-methods': 'error',
    'no-commented-out-tests': 'error',
    'no-disabled-tests': 'warn',
    'no-duplicate-hooks': 'error',
    'no-expect-resolves': 'error',
    'no-export': 'error',
    'no-focused-tests': 'error',
    'no-hooks': 'off',
    'no-identical-title': 'error',
    'no-if': 'error',
    'no-jasmine-globals': 'error',
    'no-jest-import': 'error',
    'no-large-snapshots': [
      'error',
      {
        maxSize: 50,
        inlineMaxSize: 10,
      },
    ],
    'no-mocks-import': 'error',
    'no-standalone-expect': 'error',
    'no-test-callback': 'error',
    'no-test-prefixes': 'error',
    'no-test-return-statement': 'error',
    'no-truthy-falsy': 'error',
    'no-try-expect': 'error',
    'prefer-called-with': 'warn',
    'prefer-expect-assertions': 'off',
    'prefer-hooks-on-top': 'error',
    'prefer-inline-snapshots': 'off',
    'prefer-spy-on': 'off',
    'prefer-strict-equal': 'error',
    'prefer-to-be-null': 'error',
    'prefer-to-be-undefined': 'error',
    'prefer-to-contain': 'error',
    'prefer-to-have-length': 'error',
    'prefer-todo': 'error',
    'require-top-level-describe': 'error',
    'require-to-throw-message': 'error',
    'valid-describe': 'error',
    'valid-expect-in-promise': 'error',
    'valid-expect': 'error',
    'valid-title': 'error',
  },
};
